cdr_billing:
  mode: production
  class: cdr_billing
  queue: cdr_billing
  consumer: cdr_billing
  syslog_program_name: "YETI-cdr-billing"
  mail_to: "bug-report@yeti-switch.org"
  mail_from: "yeti-cdr-billing@example.com"
  mail_subject: "Exception happened in CDR billing"

http:
  mode: production
  class: http_example
  queue: cdr_billing
  consumer: cdr_billing
  syslog_program_name: "YETI-cdr-billing"
  mail_to: "bug-report@yeti-switch.org"
  mail_from: "yeti-cdr-billing@example.com"
  mail_subject: "Exception happened in CDR billing"

